// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teybryxmmorclmsdsbao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRleWJyeXhtbW9yY2xtc2RzYmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDI0OTMsImV4cCI6MjA2NzAxODQ5M30.l4xQLUocowMUwln1UwUw498HwbwlwEfHn65sAs6Zi98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});